# Generated by Chef for localhost.
# Local modifications will be overwritten.




# Set the server root password. This should be preseeded by the package installation.
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('YbZvCONJ2_6Cm8NzpGHk');


FLUSH PRIVILEGES;
